version: '3.8'

services:
  backend:
    build:
      context: ./strapi-controle
    container_name: strapi-backend
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-controle:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./vue-project
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  ts-backend:
    image: tailscale/tailscale:latest
    container_name: ts-backend
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container1
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-backend-var-lib:/var/lib/tailscale
    network_mode: "service:backend"
    depends_on:
      - backend

  ts-frontend:
    image: tailscale/tailscale:latest
    container_name: ts-frontend
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-frontend-var-lib:/var/lib/tailscale
    network_mode: "service:frontend"
    depends_on:
      - frontend

volumes:
  tailscale-backend-var-lib:
  tailscale-frontend-var-lib:

