version: '3.8'
services:
  backend:
    build:
      context: ./strapi-controle
    container_name: strapi-backend
    ports:
      - "1337:1337"
    volumes:
      - ./strapi-controle:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./vue-project
    container_name: vue-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  ts-backend:
    image: tailscale/tailscale:latest
    container_name: ts-backend
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container1
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - ${PWD}/tailscale/config:/config
    network_mode: "service:backend"
    depends_on:
      - backend

  ts-frontend:
    image: tailscale/tailscale:latest
    container_name: ts-frontend
    cap_add:
      - net_admin
      - sys_module
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /dev/net/tun:/dev/net/tun
      - ${PWD}/tailscale/state:/var/lib/tailscale
      - ${PWD}/tailscale/config:/config
    depends_on:
      - frontend

volumes:
  frontend:
    driver: local
  ts-frontend:
    driver: local
  backend:
    driver: local
  ts-backend:
    driver: local

