name: Docker Compose CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Check if Docker Compose is installed
      id: check_docker_compose
      run: |
        if command -v docker-compose &> /dev/null; then
          echo "Docker Compose is already installed."
          echo "::set-output name=installed::true"
        else
          echo "Docker Compose is not installed."
          echo "::set-output name=installed::false"
        fi

    - name: Install Docker Compose
      if: steps.check_docker_compose.outputs.installed == 'false'
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and start containers
      run: |
        sudo docker-compose -f "docker-compose.yml" up -d

    - name: Check ts front
      run: docker container logs ts-frontend